services:
  app:
    build:
      context: .  # Build from the root directory
      dockerfile: Dockerfile  # Use the Dockerfile at the root
    container_name: app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge